[package]
name = "midi-seq-consistency-test"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Matthew Scheffel <matt@dataheck.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.9.1"
